name: github-actions
on: [push, pull_request]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '16'
          flags: --immutable-cache
      - run: yarn install
      - run: yarn build
